### ISSUE TITLE
Cannot import name 'simps' from 'scipy.integrate'

### ISSUE THREAD

**Issue by lakecity** [magic-sph/magic#48]
For Python 3.12

from magic import *

gives error: 

ImportError: cannot import name 'simps' from 'scipy.integrate' (/usr/lib/python3.12/site-packages/scipy/integrate/__init__.py)

It looks like that now "simps" should be changed to "simpson".

**Comment by AnkitBarik** [comment]
Thanks for pointing this out! Fixed in 8d3462d .

**Comment by tgastine** [comment]
Wait a second, the fix does not work. You cannot simply replace "simps" by "simpson" otherwise you'll destroy the backward compatibility with older scipy versions.

**Comment by lakecity** [comment]
Python 3.12 does not work, the same for 

ImportError: cannot import name 'trapz' from 'scipy.integrate' (/usr/lib/python3.12/site-packages/scipy/integrate/__init__.py)

**Comment by AnkitBarik** [comment]
Looks like they changed it to [`trapezoid`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.trapezoid.html#scipy.integrate.trapezoid), I'll combine the two for backwards compatibility and push a fix.

**Comment by AnkitBarik** [comment]
Push a fix in 5587f18 . Let us know if that works!

**Comment by lakecity** [comment]
Thank you, it works...next step:

cmb = MagicCoeffCmb(precision=np.float64,tag='2')

leads to

module 'numpy' has no attribute 'product'

should it be just "prod"?

**Comment by tgastine** [comment]
@lakecity : could you put the full error message? I don't see any calls to np.product in the source code of coeff.py

**Comment by lakecity** [comment]
sorry: in npfile.py

**Comment by tgastine** [comment]
Ok I just replaced it by `np.prod` . Hope this is fine now.

**Comment by lakecity** [comment]
Works! Thank you!!

**Comment by tgastine** [comment]
I'm actually not convinced the fixes pushed for `simps` and `trapz` actually work and an error will likely bump on the first call to those functions. It seems that they change the API such that if you pass 2 arguments to `simpson` like `simpson(y,x)` it won't work any more as it used to do with `simps`, you have to specify something like
`simpson(y,x=x)`. It's likely the same for `trapezoid`.

**Comment by AnkitBarik** [comment]
Just tested with `scipy 1.14` @tgastine is right, it throws an error unless `x=x` is specified. I think the best fix would be to universally use `simpson(y,x=x)` and `trapezoid(y, x=x)` - these function names have existed with this call signature as far back as [scipy v1.8](https://docs.scipy.org/doc/scipy-1.8.0/reference/generated/scipy.integrate.trapezoid.html) .

**Comment by tgastine** [comment]
I would argue specifying `simps(y,x=x)` is a bit better. This would ensure an even better backward compatibility right?

**Comment by AnkitBarik** [comment]
Okay, good point. Pushing a fix in a bit.

**Comment by AnkitBarik** [comment]
Fixed in 2a16ba9

**Comment by tgastine** [comment]
OK good job @AnkitBarik. I have the feeling this is a bug of `scipy`: the calls to `trapezoid`  still behave as they use to do with `trapz` and this is not the case for `simpson` vs `simps`.

**Comment by AnkitBarik** [comment]
@tgastine Seems like it, since their call signature is now `simpson(y,*,x=None, ...)` , with no documentation of what the `*` is supposed to be. 😄

**Comment by tgastine** [comment]
@AnkitBarik : maybe one should open an issue on scipy's github page then?

**Comment by AnkitBarik** [comment]
@tgastine Just did : https://github.com/scipy/scipy/issues/21300#issue-2443795104

**Comment by lucascolley** [comment]
`x=x` should always work, so you can safely change to that. However, there is an argument that `simpson(y, x)` is clear enough (and perhaps even more clear) than `simpson(y, x=x)`. So we'll discuss over at SciPy whether to re-allow `simpson(y, x)` in a future version.

To clarify: `*` is not a parameter (*well, technically it is an unused varargs parameter*), rather it marks all following parameters as keyword-only. See https://peps.python.org/pep-3102/.

Note: these "Expired Deprecations" were mentioned in [the 1.14.0 release notes](https://docs.scipy.org/doc/scipy/release/1.14.0-notes.html#expired-deprecations), and were announced in [the 1.12.0 release notes](https://docs.scipy.org/doc/scipy/release/1.12.0-notes.html#deprecated-features). If you maintain a package which depends on SciPy, we recommend keeping an eye on these sections of our release notes, and also testing your package with warnings enabled. In this case, these deprecations will have been emitting warnings since the start of the year.

**Comment by tgastine** [comment]
Thanks @lucascolley for your feedback! This looks like `trapezoid` accepts the old behaviour `trapezoid(y,x)`. I guess for consistency, `simpson` could behave accordingly.
